CREATE TABLE silver_processed_app_usage (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    datetime TIMESTAMP,
    timestamp VARCHAR2(50),
    event_type VARCHAR2(50),
    package_name VARCHAR2(255),
    processing_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE silver_processed_battery_status (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    status VARCHAR2(255),
    battery_level NUMBER,
    processing_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
