CREATE TABLE silver_processed_app_usage (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    datetime TIMESTAMP,
    timestamp VARCHAR2(50),
    event_type VARCHAR2(50),
    package_name VARCHAR2(255),
    processing_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE silver_processed_battery_status (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    "AC_powered" VARCHAR2(255),
    "USB_powered" VARCHAR2(255),
    "Wireless_powered" VARCHAR2(255),
    "Dock_powered" VARCHAR2(255),
    "Max_charging_current" VARCHAR2(255),
    "Max_charging_voltage" VARCHAR2(255),
    "Charge_counter" VARCHAR2(255),
    "status" VARCHAR2(255),
    "health" VARCHAR2(255),
    "present" VARCHAR2(255),
    "level" NUMBER,
    "scale" NUMBER,
    "voltage" NUMBER,
    "temperature" NUMBER,
    "technology" VARCHAR2(255),
    "batteryMiscEvent" VARCHAR2(255),
    "batteryCurrentEvent" VARCHAR2(255),
    "mSecPlugTypeSummary" VARCHAR2(255),
    "LED_Charging" VARCHAR2(255),
    "LED_Low_Battery" VARCHAR2(255),
    "current_now" VARCHAR2(255),
    "Adaptive_Fast_Charging_Settings" VARCHAR2(255),
    "Super_Fast_Charging_Settings" VARCHAR2(255),
    "FEATURE_WIRELESS_FAST_CHARGER_CONTROL" VARCHAR2(255),
    "mWasUsedWirelessFastChargerPreviously" VARCHAR2(255),
    "mWirelessFastChargingSettingsEnable" VARCHAR2(255),
    processing_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);








